#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Tue Apr 21 14:37:44 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.btnStart = wx.Button(self, wx.ID_ANY, _("Start"))
        self.btnStop = wx.Button(self, wx.ID_ANY, _("Stop"))
        self.btnClear = wx.Button(self, wx.ID_ANY, _("Clear"))
	self.btnPrint = wx.Button(self, wx.ID_ANY, _("Print"))
        self.lstMain = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_REPORT | wx.SUNKEN_BORDER)
	self.lstMain.InsertColumn(0, "No.",width=50)
	self.lstMain.InsertColumn(1, "Time")
	self.lstMain.InsertColumn(2, "Source",width=125)
	self.lstMain.InsertColumn(3, "Destination",width=125)
	self.lstMain.InsertColumn(4, "Protocol")
	self.lstMain.InsertColumn(5, "Length")
	self.lstMain.InsertColumn(6, "Info",width=250)
        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btnStart_Click, self.btnStart)
        self.Bind(wx.EVT_BUTTON, self.btnStop_Click, self.btnStop)
        self.Bind(wx.EVT_BUTTON, self.btnClear_Click, self.btnClear)
	self.Bind(wx.EVT_BUTTON, self.btnPrint_Click, self.btnPrint)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("frame_1"))
        self.SetSize((800, 600))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.btnStart, 0, wx.FIXED_MINSIZE, 0)
        sizer_3.Add(self.btnStop, 0, wx.FIXED_MINSIZE, 0)
        sizer_3.Add(self.btnClear, 0, wx.FIXED_MINSIZE, 0)
	sizer_3.Add(self.btnPrint, 0, wx.FIXED_MINSIZE, 0)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        sizer_2.Add(self.lstMain, 16, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def btnStart_Click(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'btnStart_Click' not implemented!"
        event.Skip()

    def btnStop_Click(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'btnStop_Click' not implemented!"
        event.Skip()

    def btnClear_Click(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'btnClear_Click' not implemented!"
        event.Skip()

    def btnPrint_Click(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'btnPrint_Click' not implemented!"
        event.Skip()

# end of class MyFrame
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
